import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const stylesApp = {
  // Main
  container: 'padding-xxl',
  main: 'display-flex flex-direction-column justifiy-content-center align-items-center padding-top-xxl padding-bottom-xxl min-height-100vh',
  title: 'font-size-h1 text-align-center font-weight-800',
  link: 'color-primary-7 ',
  description: 'text-align-center margin-xxl line-height-m font-size-m',

  // Card
  grid: 'display-flex align-items-center justify-content-center flex-wrap',
  card: {
    main: 'margin-m padding-l border-radius-s text-align-left color-inherit text-decoration-none border-style-solid border-width-1 border-grey-9 font-size-s',
    title: 'margin-bottom-s font-size-l font-weight-800',
    content: 'line-height-m'
  },
}

export default function Home() {
  return (
    <div className={stylesApp.container}>
      <Head>
        <title>SIUX Studio + Next.js Integration</title>
        <link href="https://cdn.siux.studio/static/brand/632213d5a467b1178b31dde0/latest/siux.main.css" type="text/css" rel="stylesheet" />
        <link href="https://cdn.siux.studio/static/brand/632213d5a467b1178b31dde0/latest/siux.main.responsive.css" type="text/css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Inter:100,200,300,400,500,600,700,800,900|Overpass+Mono:400" type="text/css" rel="stylesheet" />
        <link href="https://app.siux.studio/css/remixicon.css" type="text/css" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={stylesApp.main}>
        <h1 className={stylesApp.title}>
          <div>
            <a href="https://siux.studio" className={stylesApp.link}>SIUX Studio</a> +
            <a href="https://nextjs.org" className={stylesApp.link}> Next.js</a>
          </div>
        </h1>

        <p className={stylesApp.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={stylesApp.grid} style={{ maxWidth: '800px' }}>
          <a href="https://nextjs.org/docs"
            className={stylesApp.card.main}
            style={{ maxWidth: '300px' }}
          >
            <h2 className={stylesApp.card.title}>Documentation &rarr;</h2>
            <p className={stylesApp.card.content}>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn"
            className={stylesApp.card.main}
            style={{ maxWidth: '300px' }}
          >
            <h2 className={stylesApp.card.title}>Learn &rarr;</h2>
            <p className={stylesApp.card.content}>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={stylesApp.card.main}
            style={{ maxWidth: '300px' }}
          >
            <h2 className={stylesApp.card.title}>Examples &rarr;</h2>
            <p className={stylesApp.card.content}>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={stylesApp.card.main}
            style={{ maxWidth: '300px' }}
          >
            <h2 className={stylesApp.card.title}>Deploy &rarr;</h2>
            <p className={stylesApp.card.content}>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
